version: '2'

services:
  teamcity-server-instance:
    image: 'jetbrains/teamcity-server'
    ports:
      - "8081:8111"
    container_name: teamcity-server
    volumes:
      - /var/teamcity/datadir:/data/teamcity_server/datadir
      - /var/teamcity/logs:/opt/teamcity/logs
